### ISSUE TITLE
Component does not follow Angular standards

### ISSUE THREAD

**Issue by gado704555** [pqina/angular-filepond#1]
Your library is awesome! but your document very bad
When I install your lib by npm , your document tell me 'You can use the <FilePond>' but!!! It's error, and your readme on git cannot anything

I think it will be better if your document is cleary to installation and used.

**Comment by rikschennink** [comment]
Hi @gado704555, I'm not sure what you mean with:
> 'You can use the ' but!!! It's error, and your readme on git cannot anything

Can you try to describe the problem more clearly?

**Comment by kairauer** [comment]
Lets look at PrimeNG as an example: [PrimeNG Dropdown](https://www.primefaces.org/primeng/#/dropdown)
If you install PrimeNG via npm the only thing you need to do to use the components is to add the corresponding module as an import to your module.
I think it would be a great way to provide something like a `FilepondModule`. This module will declare _and_ export the `FilePond` component.

Other than that I would replace
`import { registerPlugin } from './filepond/filepond';`
with 
`import { registerPlugin } from 'filepond';`

And at least for me, the other import provided in your documentation, this one:
`import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type/...` 
didn't work at all. I had to install `filepond-plugin-file-validate-type` via npm. This should be included in your package.json as a dependency if you put it like this in your documentation.

Other than that, thanks for this amazing component, looking forward to use the angular component but I couldn't get it running.

**Comment by rikschennink** [comment]
Thanks @kairauer! I've been trying to restructure the component this morning but it's quite a hassle. 

Will correct the `import` statement in the readme right now.

**Comment by rikschennink** [comment]
@gado704555 @kairauer I've updated the readme and the component itself, let me know if this solves the issue.

@kairauer Plugins should be installed from npm separately, I'll describe this more clearly.

**Comment by kairauer** [comment]
@rikschennink thanks, this is much better now. 
One little thing: 

```
import { FilePond, registerPlugin } from 'angular-filepond';
```

Should be
```
import { FilePondModule, registerPlugin } from 'angular-filepond';
```

And then `FilePondModule` needs to be imported.

Got it working with the new documentation. Good work!

**Comment by rikschennink** [comment]
@kairauer Glad to hear that!

When I switch to `FilePondModule` instead of `FilePond` I get this error.

*Unexpected module 'FilePondModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.*

I don't have a lot of experience with Angular, I'm probably making a mistake somewhere but I'm not sure why it's working on your install and not on mine ( I'm using the latest version angular-cli )

**Comment by xmlking** [comment]
@rikschennink Thanks for this great liberty.
The   pull request [PR](https://github.com/xmlking/ngx-filepond) can package this lib properly as per Angular best practices. 
[ng-packager](http://spektrakel.de/ng-packagr/#slide=1) is the de-facto standards for distributing  angular libs.  
I might be able to help with future PRs  if needed.

 How to build/test/and publish:
```bash
#  integration testing
npm run serve:integration
# build
npm run build
# docs
npm run doc:buildandserve
# format, lint
npm run format
#publish 
npm run publish:dev 
npm run publish:tagged
```

**Comment by rikschennink** [comment]
@xmlking That is amazing! Thanks so much. I'll see if it works on my test project and if so will merge ASAP.

> I might be able to help with future PRs if needed.

That is very much appreciated as I don't have a lot of experience with Angular.

I've also just created a placeholder for ngx-filepond on npm ( as I understand ngx is the prefered naming convention for angular 2+ projects ). Maybe the current repository can be used for the Angular 1.x version of FilePond.

**Comment by rikschennink** [comment]
@xmlking I've tried to npm install the component but it's not working. After adding the module it throws this error in the dev console: **Uncaught Error: Unexpected module 'FilePondModule' declared by the module 'AppModule'. Please add a @Pipe/@Directive/@Component annotation.**

```bash
npm i @xmlking/ngx-filepond
```

```js
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

import { FilePondModule, registerPlugin } from '@xmlking/ngx-filepond';

// Registering plugins
import * as FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';

registerPlugin(FilePondPluginFileValidateType);

// Adding FilePond to imports
@NgModule({
  declarations: [
    AppComponent,
    FilePondModule
  ],
  imports: [
    BrowserModule
  ],
  providers: [
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
```

**Comment by xmlking** [comment]
Please see working example https://github.com/xmlking/nx-starter-kit/blob/master/libs/experiments/src/experiments.module.ts
Demo https://xmlking.github.io/nx-starter-kit/index.html

**Comment by xmlking** [comment]
@rikschennink I restructured the project using standard `angular-cli@6`, without doing any special customization.  `angular-cli@6` includes  ability to build and publish libs. 
I published at `@xmlking/ngx-filepond` and tested in my own app. it works fine.

Please let me know if you see any issues are need any help. Hoping you accept the PR and publish at `@pqina/ngx-filepond`

**Comment by rikschennink** [comment]
@xmlking I appreciate it, sorry I haven't responded earlier, super busy times. Will test this again as soon as possible.

**Comment by rikschennink** [comment]
@xmlking Just tested, it works, awesome! 

I appreciate your suggested changes but do have some questions:

- Will this work with older version of Angular (2+)?

- I'd like to remove the plugin dependencies, these should be installed separately. As the list will grow it would mean having to maintain it in separate places.

- There will be more plugins with CSS dependencies, while I love that it's not needed to embed the CSS manually, I'm not in favour of adding all CSS dependencies to `filepond.component.scss`. For now, let's have the CSS files as a separate entry in the `angular.json` configuration file. If you've got other suggestions I'm all ears.

- I'm publishing at `ngx-filepond` does that impact any of the changes (apart from the library import itself?)

- The props will also grow dynamically based on the number of plugins loaded, so it's best to remove these from the `AfterViewInit` method as maintaining these props in both the FilePond core library and in this plugin is prone to errors. If you can add the props dynamically that would be nice (I do this in the Vue adapter).

- I don't understand why the repo has a `src/app/` folder, I would like to limit it as much as possible to only be the FilePond adapter, is there any reason to have an app in there as well?

- The `src/browserlist` file indicates that it excludes IE11 support. Since FilePond does support IE11 it should be adjusted for IE11.


Readme:

- I'd like to omit the link to the generated docs as I'm keeping all the docs at https://pqina.nl/filepond/docs

- The Development section can be left out, let's keep it as concise as possible.

**Comment by aitorllj93** [comment]
Hi, thanks for your awesome library

I tried your adapter and got errors when running ```ng build --prod``` on angular 5.

Then, I tried with @xmlking version and got errors too. Copying component to my project works well. I think Angular 6 compilations aren't compatible with previous versions.

If you want more details please contact me

**Comment by rikschennink** [comment]
@aitorllj93 Yeah, I'm still kinda struggling to get my head around the whole Angular bonanza. I've got a React, Vue and jQuery wrapper all fully functional without much hassle, but Angular seems to be a whole different thing. 

If you have a link to an up-to-date, lean-and-mean, plugin template GitHub repository, that would be amazing.

**Comment by aitorllj93** [comment]
Hi, @rikschennink 
I'm currently on a deadline, but when I get time I can help you with this. I've changed some code on the wrapper inside our project in order to solve some issues related to events emitting

**Comment by xmlking** [comment]
@aitorllj93 @rikschennink  I pushed new build with angular-cli 6.0.1 which might fix some of the issues we are facing. So for I don't  see any issues using this new build. in case you have issues, remove `node_modules` and `package-lock.json` and then run `npm install` again. 

Note: I am following [How to build a library for Angular apps?](https://medium.com/@tomsu/how-to-build-a-library-for-angular-apps-4f9b38b0ed11) and angular-cli [create-library](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/create-library.md) standard docs  

> Will this work with older version of Angular (2+)?

you can make it work for angular 2-6 by setting `projects/@pqina/ngx-filepond/package.json` 
```json
  "peerDependencies": {
    "@angular/common": ">=5.0.0 <7.0.0",
    "@angular/core": ">=5.0.0 <7.0.0"
  }
```
this is the `package.json` file that get published. So you can edit it as per your needs. 
the project root `package.json` is not used for publishing.
  
> I'd like to remove the plugin dependencies, these should be installed separately. As the list will grow it would mean having to maintain it in separate places.

> There will be more plugins with CSS dependencies, while I love that it's not needed to embed the CSS manually, I'm not in favour of adding all CSS dependencies to filepond.component.scss. For now, let's have the CSS files as a separate entry in the angular.json configuration file. If you've got other suggestions I'm all ears.

Agree.  you can remove plugin CSS in  `projects/@xmlking/ngx-filepond/src/lib/filepond.component.scss`  
I feel we should at least keep `@import 'node_modules/filepond/dist/filepond.css';`  as this reduce one more step the end user  need to follow for minimal usecase.

> I'm publishing at ngx-filepond does that impact any of the changes (apart from the library import itself?)

No impact, change the name in `projects/@xmlking/ngx-filepond/package.json`. I was just using my namespace for my convenience.

> The props will also grow dynamically based on the number of plugins loaded, so it's best to remove these from the AfterViewInit method as maintaining these props in both the FilePond core library and in this plugin is prone to errors. If you can add the props dynamically that would be nice (I do this in the Vue adapter).

This is a bit tricky.  I also like dynamic input/outputs but I faced  problem during --prod builds (AOT)
 dynamic input/outputs works fine for dev builds (JIT).  **need to research**

> I don't understand why the repo has a src/app/ folder, I would like to limit it as much as possible to only be the FilePond adapter, is there any reason to have an app in there as well?

`src/app` is for integration tests. you can quickly test your lib changes with just `ng serve` command.  We can rename it to `integration/app` if you prefer, like    [ngxs](https://github.com/ngxs/store). 
I see this trend: unit tests for lib stay in `projects/@pqina/ngx-filepond/src/lib` i.g., `*.spec.ts` files close to source files. integration  tests in `integration/app` or `src/app` (angular-cli default)

> The src/browserlist file indicates that it excludes IE11 support. Since FilePond does support IE11 it should be adjusted for IE11.

This is for your `integration` test app. this will not impact how end developer use it.  you can change whatever you want.  This will not be bundled into final `npm` package.  
 
Readme:

> I'd like to omit the link to the generated docs as I'm keeping all the docs at https://pqina.nl/filepond/docs
agree. I removed `/docs` in latest PR. I was expecting you will modify `README.md` file based on your preference. since I don't know, just left some notes for you.

> The Development section can be left out, let's keep it as concise as possible.

Agree , I  left it there as temp notes for contributors .

**Comment by aitorllj93** [comment]
Hi @xmlking, my biggest issue is with dynamic outputs on production builds. Angular AoT compiler just seems to ignore props without annotations and subscriptions won't be triggered.

Another issue I've faced is that event subscriptions don't receive arguments because this line:

```ts
this[output].emit(output, ...args);
```
As far I know about RxJS, you can't send multiple arguments, so I always get output name, but no args. This is easily fixed by only emitting args. I don't see the case where event name would be a need.

**Comment by xmlking** [comment]
ya,  AoT compiler doesn't like dynamic inputs/outputs. I haven't tested  the output events yet.

**Comment by rikschennink** [comment]
@xmlking @aitorllj93 Is there some way we could create the component at runtime (without any heavy dependencies)? I've recently updated the Vue adapter to a function that returns a newly created component (based on the properties required for the plugins). The function takes the required plugins as parameters, it then dynamically creates inputs and ouputs, builds and returns the component. Would that work for Angular as well?

**Comment by xmlking** [comment]
Looks like angular supports dynamic components. Not sure what is the minimum version needed 
https://angular.io/guide/dynamic-component-loader


-Sumanth

**Comment by aitorllj93** [comment]
@rikschennink, @xmlking I've worked with dynamic components loading but I don't think it could work. Dynamically loaded components need to be defined on the same way that other components (with ```@Inputs``` and ```@Outputs```). The component loader only handles the process of instantiating those predefined components. Also, it's pretty hacky because you lose databinding and must handle events subscription in a more programmatic way. I can't recommend this approach. 

Another option would be to expose one single ```@Output``` emitting an object like this:

```js
{
  "event": "eventName",
  "params/args": []
}
```

You can also provide an ```@Input``` with library config, including the callbacks for events. This approach is used on framework agnostic components like ag-grid.

**Comment by rikschennink** [comment]
@aitorllj93 Thanks for chiming in, that indeed sounds like it wouldn't work.

Having a single options `@input` would be the most straightforward and flexible solution but would also be less familiar for Angular devs I guess?

**Comment by xmlking** [comment]
I noticed some developers are following convention like 
```ts
@Input('config'): Config;  //immutable 
@Input('data') : DataSource; //mutable 
```
What do you guys think about something like this?
if you what to provide developers  type safe config, then we can define `Config` interface and  declare `@Input('config') config: Config`

```ts
  @Input('config') config: Object = {
    id: 'myfileUplooad',
    className: "myfileUplooadClass",
    allowDrop: true,
    maxFiles: 3,
    imagePreview: {
      allowPreview : true,
      minHeight: 200,
      maxHeight: 100,
      Height: 100,
      maxFileSize: '5k'
    }
   ...
  }
```

**Comment by rikschennink** [comment]
@xmlking That would work I think. Although adding the interface would require updating the interface for each plugin ( doing this for third-party plugins, when they become possible, might be tedious ).

**Comment by aitorllj93** [comment]
I like the @xmlking proposal. Although it's not very Angular friendly it's the approach I've seen on most framework agnostic components because it allows maintainers upgrade the core module without touching the framework adapters. Users can create their own wrappers if they need more dynamic inputs/outputs (This is something I do with external components in order to wrap application wide configs)

About the Config interface I would put it on the core module, so you only have one single file to update. If you want users have one single import, just export it on adapters

**Comment by rikschennink** [comment]
@xmlking @aitorllj93 I've been working on a new version of the component following the [suggestions in this article](https://medium.com/@nikolasleblanc/building-an-angular-4-component-library-with-the-angular-cli-and-ng-packagr-53b2ade0701e).

It features two `@Input` parameters, `options` and `files`. I've statically defined all the FilePond `@Output` properties ( `oninit`, `onaddfile`, etc. ) to events. The `event.detail` object is then passed to the `emit` method. 

I've tested it in development mode and in prod mode and it seems to work. Indeed dynamically extracting the properties form the FilePond options object doesn't work in `--prod` mode.

I find `ng-packagr` doesn't correctly copy the `name` and `version` from the `ng-package.json` which is annoying. Maybe I'm missing something obvious there.

Will publish as soon as possible.

**Comment by rikschennink** [comment]
@xmlking @aitorllj93 npm was having some trouble this afternoon, it should work now.

```
npm install ngx-filepond --save
```

This should install version `2.0.0`, please check if it does, due to the issues with npm it kept installing version `0.0.1` which doesn't work.

Add filepond styles path `./node_modules/filepond/dist/filepond.min.css` to the `build.options.styles` property in `angular.json`

```html
<!-- app.component.html -->
<file-pond #myPond 
    [options]="pondOptions" 
    [files]="pondFiles"
    (oninit)="pondHandleInit()"
    (onaddfile)="pondHandleAddFile($event)">
</file-pond>
```

```ts
// app.component.ts
import { Component, ViewChild } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {

  @ViewChild('myPond') myPond: any;

  pondOptions = {
    class: 'my-filepond',
    multiple: true,
    labelIdle: 'Drop files here',
    acceptedFileTypes: 'image/jpeg, image/png'
  }

  pondFiles = [
    'index.html'
  ]

  pondHandleInit() {
    console.log('FilePond has initialised', this.myPond);
  }

  pondHandleAddFile(event: any) {
    console.log('A file was added', event);
  }
}
```

```ts
// app.module.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

// import filepond module
import { FilePondModule, registerPlugin } from 'ngx-filepond';

// import and register filepond file type validation plugin
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
registerPlugin(FilePondPluginFileValidateType);

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FilePondModule // add filepond module here
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**Comment by rikschennink** [comment]
I've moved the repository to [pqina/ngx-filepond](https://github.com/pqina/ngx-filepond), will deprecate this repository.

**Comment by aitorllj93** [comment]
I will give it a try when I've some free time.
Thanks for your work
